### ISSUE TITLE
Make Email Registrations Optional Again

### ISSUE THREAD

**Issue by whoarethesevoices** [anope/anope#383]
With configurations that cannot utilize a mail transfer agent, the entire email compartment of anope should be optional.

Users may not wish to provide an email address. Operators may not want their services to depend on users providing email addresses. Previously it was possible for operators to confirm user accounts manually.

Forcing users to provide a bogus email address, or adding those on the system side automatically is far from ideal...

**Comment by SadieCat** [comment]
As I mentioned on IRC networks which do not require an email address are very unusual in 2024. I'm not against having options but options that are almost entirely unused results results in unnecessary maintenance burden and edge cases from things not being tested properly. 

For the vast majority of networks there is no harm in collecting an email address for users even if email confirmation is not enabled. It allows admins to have ways to communicate with their users out of band and verify their identity even if it isn't done by services. Almost every online service nowadays does this so its expected behaviour for users.

If you still *really* don't want to collect email addresses there is no reason why you can't just use [the rewrite module](https://wiki.anope.org/index.php/2.0/Modules/m_rewrite) to add something like `nocontact@yournetwork.com` when a user registers without an email address.

**Comment by TehPeGaSuS** [comment]
> Previously it was possible for operators to confirm user accounts manually.

It is still possible to confirm the accounts manually by admins. just set [this line](https://github.com/anope/anope/blob/2.1/data/nickserv.example.conf#L448) to `admin`.

Even on a I2P/Tor only network, having users providing emails is a security feature. This allows admins to be sure that the the users trying to recover the account, reset the password, etc, is the true owner and not an impostor.

**Comment by whoarethesevoices** [comment]
> It is still possible to confirm the accounts manually by admins. just set [this line](https://github.com/anope/anope/blob/2.1/data/nickserv.example.conf#L448) to `admin`.

The point was, that there is a mechanism to prevent abuse, when email verification is disabled.

> Even on a I2P/Tor only network, having users providing emails is a security feature. This allows admins to be sure that the users trying to recover the account, reset the password, etc, is the true owner and not an impostor.

The point is, that emails are enforced, even on a system where there is no mail rig in place.

If "we" go this Atheme-fication route... take a look at https://github.com/atheme/atheme/issues/900 then...

**Comment by TehPeGaSuS** [comment]
If you set [registration](https://github.com/anope/anope/blob/2.1/data/nickserv.example.conf#L448) to `none` or `admin` then no email is sent.
Therefore no need to have an email system.

**Comment by whoarethesevoices** [comment]
> If you set [registration](https://github.com/anope/anope/blob/2.1/data/nickserv.example.conf#L448) to `none` or `admin` then no email is sent. Therefore no need to have an email system.

Exactly.

**Comment by SadieCat** [comment]
> If "we" go this Atheme-ification route... take a look at atheme/atheme#900 then...

That nobody else has commented on this in almost a year suggests that there isn't really a demand for it.

The .invalid TLD is reserved so it will never point to a real host and if you use rewrite (a feature Atheme does not have) like I mentioned your users won't even need to do it manually.

**Comment by whoarethesevoices** [comment]
Would it be possible to make it "optional" again, with m_rewrite. Where users can decide for themselves if they want to pass an email address as an argument?

And what are these edge cases about? It was working "just fine" before it was removed.

**Comment by TehPeGaSuS** [comment]
Here's what I was thinking about. On the `ns_register` we currently have 3 options on the `registration` part:
- **admin** - which requires manual confirmation by an admin
- **mail** - where it sends an email to the user with a code that ust be used with the `/NS CONFIRM <code>`
- **none** - the user is instantly registered, without any kind of confirmaton required.

Here's my proposal:
- Add an option like `noemail` to `registration`. With this option, the network admins can provide a fake email that will be used IF the users doesn't provide an email adress. IF the user provides an email address (which would be optional) then the email address provided is used instead.

Possible configuration block:
```
module
{
	name = "ns_register"

	/*
	 * Registration confirmation setting. Set to "none" for no registration confirmation,
	 * "mail" for email confirmation, and "admin" to have services operators manually confirm
	 * every registration and "noemail" which behaves like "none" but doesn't require users to
	 * provide an email address. Set to "disable" to completely disable all registrations.
	 */
	registration = "none"
	
	/* Fake email setting. This email address will be used if `registration = "noemail"` and
	 * IF the user does not provide an email address. IF the user provides
	 * an email address, then the provided email address will be used instead.
	 */
	 fakemail = "users@network.tld"

	/*
	 * The minimum length of time between consecutive uses of NickServ's RESEND command.
	 *
	 * This directive is optional, but recommended. If not set, this restriction will be disabled.
	 */
	resenddelay = 90s

	/*
	 * Prevents users from registering their nick if they are not connected
	 * for at least the given number of seconds.
	 *
	 * This directive is optional.
	 */
	nickregdelay = 15s

	/*
	 * The length of time a user using an unconfirmed account has
	 * before the account will be released for general use again.
	 */
	#unconfirmedexpire = 1d
}
```

**Comment by Techman** [comment]
I want this feature to still exist in Anope. While I agree that most conventional networks will probably want to use email addresses, email has never been required for IRC registrations, and IRC can exist without email. Users who do not supply one should consider their accounts forfeited if they forget the password and staff cannot verify using other means.

While it may be possible to specify a dummy address, it still feels arbitrary. I like the idea of #385, though. Specifying a backend ***or*** no backend would solve this case. Until then, I would like emails to remain optional.

**Comment by GTAXL** [comment]
While for my network I require e-mail addresses for registration, I can understand others frustrations with this feature being removed from Anope. How long has this feature of being able to not require an e-mail been a feature? I'm guessing a long time. This is not a new feature that brings a bunch of potential bugs. I'm curious how keeping it has edge cases. How much more testing does a feature need that's always existed? You also have to consider existing databases and not introducing breaking changes. How will it handle a network that's always not had e-mail tied to a nickserv account?

I've also heard TOR being brought up and as a concern. Well if someone is using TOR, the purpose of that is to anonymize themselves. Providing an e-mail illegitimizes the purpose of TOR.

The concern of not having this requirement is that bots can potentially register accounts. Well there is admin verify, which would be a legitimate option for a network that doesn't require e-mail addresses. Even if you do require an e-mail, and with e-mail confirmation, a bot could still just populate this field, listen on port 25 and act as an MTA, watch for inbound emails and parse the confirmation. If you are trying to secure nickserv registration via IRC command line, it's still vulnerable. The best way is to have a web front-end with CAPTCHA and e-mail confirmation. That's beyond the scope of this discussion, but I just found it rather silly people think e-mail confirmation on Anope stops real botnets.

I also saw the "solution" of using bogus e-mails instead of a real e-mail address. I find this silly to store arbitrary data that is false. If a user chooses to provide an e-mail, we should verify it as so. If they chose not to provide an e-mail, so be it. I will know if the nick has an e-mail associated, it is indeed their legitimate e-mail address.

There is also the discussion of how do we verify a person's identity if they forgot their password. Well the ns_misc fields allow storage of other arbitrary data such as twitter accounts, websites, pgp keys, xmpp, etc. Also say I want to register some bot accounts and I'm an admin, I know those nicks are legitimate as I created them, and they don't necessarily need an e-mail address tied to them.

I can understand the push back from the developer if this was a new feature being introduced and would bring potential breaking changes. I don't understand if it's already an existing feature, and has been for a long time and is being removed for, arguably no good reason. If it hasn't been tested enough in the several years it's been a feature, then I'd advise the OP to do more additional testing of such "edge cases" to kink out any bugs. Features are one thing, but removing features should really be given a lot more thought before pulling the trigger. Know what I want out of IRC software? For it to be left alone. Just provide security updates and bug fixes. But sadly we live in a world where people want change for the sake of change and to chase version numbers. Just my feedback on this discussion. For whatever it's worth.
